# Generated by Django 3.0.1 on 2019-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pinjamKU',
            fields=[
                ('id_nama', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
