# Generated by Django 3.0.1 on 2019-12-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='senjata',
            fields=[
                ('id_senjata', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_senjata', models.CharField(max_length=30)),
                ('jumlah_senjata', models.IntegerField(verbose_name=100)),
                ('jumlah_tersedia', models.IntegerField(verbose_name=100)),
            ],
        ),
    ]
