# Generated by Django 3.0.1 on 2019-12-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0002_senjata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senjata',
            name='jumlah_senjata',
            field=models.IntegerField(verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='senjata',
            name='jumlah_tersedia',
            field=models.IntegerField(verbose_name=1000),
        ),
    ]
