# Generated by Django 3.0.1 on 2019-12-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0003_auto_20191219_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id_karyawan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_karyawan', models.CharField(max_length=30)),
                ('jenis_kelamin_karyawan', models.CharField(max_length=1)),
                ('alamat_karyawan', models.CharField(max_length=50)),
                ('no_ktp_karyawan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id_peminjaman', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_peminjam', models.CharField(max_length=30)),
                ('jenis_kelamin_peminjam', models.CharField(max_length=1)),
                ('alamat_peminjam', models.CharField(max_length=50)),
                ('no_ktp_peminjam', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Produsen',
            fields=[
                ('id_produsen', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_produsen', models.CharField(max_length=30)),
                ('alamat_produsen', models.IntegerField(verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeminjamanSenjata',
            fields=[
                ('id_penyewa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_pinjam', models.DateField()),
                ('id_karyawan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.Karyawan')),
                ('id_peminjaman', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.Peminjaman')),
                ('id_senjata', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.Senjata')),
            ],
        ),
        migrations.CreateModel(
            name='DetailSenjata',
            fields=[
                ('id_detail_senjata', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_senjata', models.CharField(max_length=30)),
                ('tipe_senjata', models.CharField(max_length=30)),
                ('ipe_peluru', models.CharField(max_length=30)),
                ('nama_produsen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.Produsen')),
            ],
        ),
        migrations.AddField(
            model_name='senjata',
            name='id_detail_senjata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.DetailSenjata'),
        ),
    ]
