# Generated by Django 3.0.1 on 2019-12-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0009_auto_20191219_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_senjata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.Senjata'),
        ),
        migrations.AlterField(
            model_name='produsen',
            name='alamat_produsen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='senjata',
            name='jumlah_senjata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='senjata',
            name='jumlah_tersedia',
            field=models.IntegerField(),
        ),
    ]
