# Generated by Django 3.0.1 on 2019-12-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0012_auto_20191220_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senjata',
            name='jumlah_senjata',
        ),
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_senjata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.Senjata'),
        ),
    ]
