# Generated by Django 3.0.1 on 2019-12-23 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
        ('pinjam', '0018_auto_20191222_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_karyawan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karyawan.Karyawan'),
        ),
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_senjata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.Senjata'),
        ),
        migrations.DeleteModel(
            name='Karyawan',
        ),
    ]
