# Generated by Django 3.0.1 on 2019-12-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
        ('pinjam', '0020_auto_20191223_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjamansenjata',
            old_name='id_penyewa',
            new_name='id_penyewaan',
        ),
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_karyawan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karyawan.Karyawan'),
        ),
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_peminjaman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinjam.Peminjam'),
        ),
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_senjata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinjam.Senjata'),
        ),
    ]
