# Generated by Django 3.0.1 on 2019-12-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0021_auto_20191223_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_senjata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinjam.Senjata'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_penyewa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinjam.Peminjam')),
                ('id_senjata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinjam.Senjata')),
            ],
        ),
    ]
