# Generated by Django 3.0.1 on 2020-01-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0027_auto_20191224_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='senjata',
            name='link_image',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_senjata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinjam.Senjata'),
        ),
        migrations.AlterField(
            model_name='peminjamansenjata',
            name='id_senjata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinjam.Senjata'),
        ),
    ]
